export enum CHAMPION_CARD_CODE {
    AATROX = '06RU026',
    AHRI = '05IO004',
    AKSHAN = '04SH130',
    ANIVIA = '01FR024',
    ANNIE = '06NX012',
    APHELIOS = '03MT217',
    ASHE = '01FR038',
    AURELION_SOL = '03MT087',
    AZIR = '04SH003',
    BARD = '06RU001',
    BRAUM = '01FR009',
    CAITLYN = '05PZ006',
    DARIUS = '01NX038',
    DIANA = '03MT056',
    DRAVEN = '01NX020',
    EKKO = '04PZ001',
    ELISE = '01SI053',
    EVELYNN = '06RU025',
    EZREAL = '01PZ036',
    FIORA = '01DE045',
    FIZZ = '02BW046',
    GALIO = '05DE009',
    GANGPLANK = '02BW032',
    GAREN = '01DE012',
    GNAR = '05BC161',
    GWEN = '06SI012',
    HECARIM = '01SI042',
    HEIMERDINGER = '01PZ056',
    ILLAOI = '06BW006',
    IRELIA = '04IO005',
    JACK = '07BW002',
    JARVAN_IV = '04DE008',
    JAX = '06RU008',
    JAYCE = '05PZ022',
    JHIN = '06RU002',
    JINX = '01PZ040',
    KAISA = '06SH009',
    KALISTA = '01SI030',
    KARMA = '01IO041',
    KATARINA = '01NX042',
    KAYLE = '06MT008',
    KAYN = '06RU005',
    KENNEN = '05BC058',
    KINDRED = '04SI005',
    LEBLANC = '04NX004',
    LEE_SIN = '02IO006',
    LEONA = '03MT054',
    LISSANDRA = '04FR005',
    LUCIAN = '01DE022',
    LULU = '03IO002',
    LUX = '01DE042',
    MALPHITE = '04MT008',
    MAOKAI = '02SI008',
    MASTER_YI = '06IO008',
    MISS_FORTUNE = '02BW022',
    NAMI = '05BW005',
    NASUS = '04SH047',
    NAUTILUS = '02BW053',
    NEEKO = '07RU012',
    NIDALEE = '07SH013',
    NOCTURNE = '03SI005',
    NORRA = '06BC015',
    ORNN = '06FR011',
    PANTHEON = '05MT003',
    POPPY = '05BC041',
    PORO_KING = '06RU015',
    PYKE = '04BW005',
    QUINN = '02DE006',
    REKSAI = '04SH019',
    RENEKTON = '04SH067',
    RIVEN = '03NX007',
    RUMBLE = '05BC088',
    RYZE = '06RU006',
    SAMIRA = '07NX007',
    SEJUANI = '02FR002',
    SENNA = '05SI009',
    SERAPHINE = '06PZ021',
    SETT = '07IO011',
    SHEN = '01IO032',
    SHYVANA = '03DE011',
    SION = '05NX001',
    SIVIR = '04SH020',
    SORAKA = '03MT055',
    SWAIN = '02NX007',
    TAHM_KENCH = '03BW004',
    TALIYAH = '04SH073',
    TARIC = '03MT058',
    TEEMO = '01PZ008',
    THRESH = '01SI052',
    TRISTANA = '05BC133',
    TRUNDLE = '03FR006',
    TRYNDAMERE = '01FR039',
    TWISTED_FATE = '02BW026',
    UDYR = '05FR013',
    VARUS = '06RU009',
    VAYNE = '06DE021',
    VEIGAR = '05BC093',
    VI = '02PZ008',
    VIEGO = '04SI055',
    VIKTOR = '03PZ003',
    VLADIMIR = '01NX006',
    XERATH = '05SH014',
    YASUO = '01IO015',
    YUUMI = '05BC029',
    ZED = '01IO009',
    ZIGGS = '05BC163',
    ZILEAN = '04SH039',
    ZOE = '03MT009',
}

export type ChampionCardCode = `${CHAMPION_CARD_CODE.AATROX}`
    | `${CHAMPION_CARD_CODE.AHRI}`
    | `${CHAMPION_CARD_CODE.AKSHAN}`
    | `${CHAMPION_CARD_CODE.ANIVIA}`
    | `${CHAMPION_CARD_CODE.ANNIE}`
    | `${CHAMPION_CARD_CODE.APHELIOS}`
    | `${CHAMPION_CARD_CODE.ASHE}`
    | `${CHAMPION_CARD_CODE.AURELION_SOL}`
    | `${CHAMPION_CARD_CODE.AZIR}`
    | `${CHAMPION_CARD_CODE.BARD}`
    | `${CHAMPION_CARD_CODE.BRAUM}`
    | `${CHAMPION_CARD_CODE.CAITLYN}`
    | `${CHAMPION_CARD_CODE.DARIUS}`
    | `${CHAMPION_CARD_CODE.DIANA}`
    | `${CHAMPION_CARD_CODE.DRAVEN}`
    | `${CHAMPION_CARD_CODE.EKKO}`
    | `${CHAMPION_CARD_CODE.ELISE}`
    | `${CHAMPION_CARD_CODE.EVELYNN}`
    | `${CHAMPION_CARD_CODE.EZREAL}`
    | `${CHAMPION_CARD_CODE.FIORA}`
    | `${CHAMPION_CARD_CODE.FIZZ}`
    | `${CHAMPION_CARD_CODE.GALIO}`
    | `${CHAMPION_CARD_CODE.GANGPLANK}`
    | `${CHAMPION_CARD_CODE.GAREN}`
    | `${CHAMPION_CARD_CODE.GNAR}`
    | `${CHAMPION_CARD_CODE.GWEN}`
    | `${CHAMPION_CARD_CODE.HECARIM}`
    | `${CHAMPION_CARD_CODE.HEIMERDINGER}`
    | `${CHAMPION_CARD_CODE.ILLAOI}`
    | `${CHAMPION_CARD_CODE.IRELIA}`
    | `${CHAMPION_CARD_CODE.JACK}`
    | `${CHAMPION_CARD_CODE.JARVAN_IV}`
    | `${CHAMPION_CARD_CODE.JAX}`
    | `${CHAMPION_CARD_CODE.JAYCE}`
    | `${CHAMPION_CARD_CODE.JHIN}`
    | `${CHAMPION_CARD_CODE.JINX}`
    | `${CHAMPION_CARD_CODE.KAISA}`
    | `${CHAMPION_CARD_CODE.KALISTA}`
    | `${CHAMPION_CARD_CODE.KARMA}`
    | `${CHAMPION_CARD_CODE.KATARINA}`
    | `${CHAMPION_CARD_CODE.KAYLE}`
    | `${CHAMPION_CARD_CODE.KAYN}`
    | `${CHAMPION_CARD_CODE.KENNEN}`
    | `${CHAMPION_CARD_CODE.KINDRED}`
    | `${CHAMPION_CARD_CODE.LEBLANC}`
    | `${CHAMPION_CARD_CODE.LEE_SIN}`
    | `${CHAMPION_CARD_CODE.LEONA}`
    | `${CHAMPION_CARD_CODE.LISSANDRA}`
    | `${CHAMPION_CARD_CODE.LUCIAN}`
    | `${CHAMPION_CARD_CODE.LULU}`
    | `${CHAMPION_CARD_CODE.LUX}`
    | `${CHAMPION_CARD_CODE.MALPHITE}`
    | `${CHAMPION_CARD_CODE.MAOKAI}`
    | `${CHAMPION_CARD_CODE.MASTER_YI}`
    | `${CHAMPION_CARD_CODE.MISS_FORTUNE}`
    | `${CHAMPION_CARD_CODE.NAMI}`
    | `${CHAMPION_CARD_CODE.NASUS}`
    | `${CHAMPION_CARD_CODE.NAUTILUS}`
    | `${CHAMPION_CARD_CODE.NEEKO}`
    | `${CHAMPION_CARD_CODE.NIDALEE}`
    | `${CHAMPION_CARD_CODE.NOCTURNE}`
    | `${CHAMPION_CARD_CODE.NORRA}`
    | `${CHAMPION_CARD_CODE.ORNN}`
    | `${CHAMPION_CARD_CODE.PANTHEON}`
    | `${CHAMPION_CARD_CODE.POPPY}`
    | `${CHAMPION_CARD_CODE.PORO_KING}`
    | `${CHAMPION_CARD_CODE.PYKE}`
    | `${CHAMPION_CARD_CODE.QUINN}`
    | `${CHAMPION_CARD_CODE.REKSAI}`
    | `${CHAMPION_CARD_CODE.RENEKTON}`
    | `${CHAMPION_CARD_CODE.RIVEN}`
    | `${CHAMPION_CARD_CODE.RUMBLE}`
    | `${CHAMPION_CARD_CODE.RYZE}`
    | `${CHAMPION_CARD_CODE.SAMIRA}`
    | `${CHAMPION_CARD_CODE.SEJUANI}`
    | `${CHAMPION_CARD_CODE.SENNA}`
    | `${CHAMPION_CARD_CODE.SERAPHINE}`
    | `${CHAMPION_CARD_CODE.SETT}`
    | `${CHAMPION_CARD_CODE.SHEN}`
    | `${CHAMPION_CARD_CODE.SHYVANA}`
    | `${CHAMPION_CARD_CODE.SION}`
    | `${CHAMPION_CARD_CODE.SIVIR}`
    | `${CHAMPION_CARD_CODE.SORAKA}`
    | `${CHAMPION_CARD_CODE.SWAIN}`
    | `${CHAMPION_CARD_CODE.TAHM_KENCH}`
    | `${CHAMPION_CARD_CODE.TALIYAH}`
    | `${CHAMPION_CARD_CODE.TARIC}`
    | `${CHAMPION_CARD_CODE.TEEMO}`
    | `${CHAMPION_CARD_CODE.THRESH}`
    | `${CHAMPION_CARD_CODE.TRISTANA}`
    | `${CHAMPION_CARD_CODE.TRUNDLE}`
    | `${CHAMPION_CARD_CODE.TRYNDAMERE}`
    | `${CHAMPION_CARD_CODE.TWISTED_FATE}`
    | `${CHAMPION_CARD_CODE.UDYR}`
    | `${CHAMPION_CARD_CODE.VARUS}`
    | `${CHAMPION_CARD_CODE.VAYNE}`
    | `${CHAMPION_CARD_CODE.VEIGAR}`
    | `${CHAMPION_CARD_CODE.VI}`
    | `${CHAMPION_CARD_CODE.VIEGO}`
    | `${CHAMPION_CARD_CODE.VIKTOR}`
    | `${CHAMPION_CARD_CODE.VLADIMIR}`
    | `${CHAMPION_CARD_CODE.XERATH}`
    | `${CHAMPION_CARD_CODE.YASUO}`
    | `${CHAMPION_CARD_CODE.YUUMI}`
    | `${CHAMPION_CARD_CODE.ZED}`
    | `${CHAMPION_CARD_CODE.ZIGGS}`
    | `${CHAMPION_CARD_CODE.ZILEAN}`
    | `${CHAMPION_CARD_CODE.ZOE}`

export function isChampionCardCode(variable: any): boolean {
    return Object.values(CHAMPION_CARD_CODE).map(i => `${i}`).includes(`${variable}`);
}

export enum CARD_TYPE {
    CHAMPION = 'Champion',
    FOLLOWER = 'Follower',
    SPELL = 'Spell',
    LANDMARK = 'Landmark',
    EQUIPMENT = 'Equipment',
}

export type CardType = `${CARD_TYPE.CHAMPION}`
    | `${CARD_TYPE.FOLLOWER}`
    | `${CARD_TYPE.SPELL}`
    | `${CARD_TYPE.LANDMARK}`
    | `${CARD_TYPE.EQUIPMENT}`

export function isCardType(variable: any): boolean {
    return Object.values(CARD_TYPE).map(i => `${i}`).includes(`${variable}`);
}
