on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        description: 'Person Who Triggered'
        required: true
        default: 'gabriel-gn'

jobs:
  check-version:
    name: Check package version
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check version changes
        uses: gabriel-gn/hello-world-github-action@v1.0.1
        with:
          packageName: '@gabrielgn-test/runeterra-tools'
          filepath: './package.json'
        id: check # Usa o output checked a partir desse id
      - name: Version checked
        run: 'echo "Version -> ${{ steps.check.outputs.changed }}"'
      - name: Version update detected
        if: |
          steps.check.outputs.changed == 'true'
        run: 'echo "Versão alterada, será criada uma nova release no npm!"'
      - name: Version update not detected
        if: |
          steps.check.outputs.changed == 'false'
        run: 'echo "Versão de pacote não alterada, não será publicado no npm!"'

      - name: Generate docs
        run: |
          echo "*** Generating Docs! ***"
          npm install
          npm run docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs # The folder the action should deploy.